---
mongodb_login_host: {{ hostvars[groups['mongo_master'][0]].inventory_hostname }}
mongodb_replication_params:
  - {
      host_name: {{ hostvars[inventory_hostname].inventory_hostname }},
      host_port: "{{ mongodb_net_port }}",
      host_type: replica,
    }